### ISSUE TITLE
Missing an ActiveFedora::File#content? method

### ISSUE THREAD

**Issue by jeremyf** [projecthydra/active_fedora#1082]
At present, there are guard conditions throughout the Hydra stack (CurationConcerns and Sufia) that appear to ask the equivalent of `if original_file.content`. In the current implementation, this means reading the content from disk, regardless of size. That alone can be an expensive operation.

What options might exist for peaking at the data without a full read so we can ask if the File has content?

**Comment by jcoyne** [comment]
Can't we just ask if `original_file.nil?`
```ruby
fs = FileSet.create
fs.original_file
=> nil
```

**Comment by jeremyf** [comment]
I think the solution I'm looking for may be within [CurationConcerns](https://github.com/projecthydra-labs/curation_concerns/pull/798#discussion_r63706200)
