### ISSUE TITLE
Remove .send call from FedoraAttributes/OrderedList

### ISSUE THREAD

**Issue by tpendragon** [projecthydra/active_fedora#1111]
Remove the .send call from https://github.com/projecthydra/active_fedora/blob/f6ac3fbe04d5c0fedb64b7c04a34ca207d29f7f7/lib/active_fedora/fedora_attributes.rb#L46 and https://github.com/projecthydra/active_fedora/blob/f6ac3fbe04d5c0fedb64b7c04a34ca207d29f7f7/lib/active_fedora/orders/ordered_list.rb#L17 when ActiveTriples/ActiveTriples#222 is closed

**Comment by no-reply** [comment]
You should be able to move forward with this. Note the caveats in https://github.com/ActiveTriples/ActiveTriples/issues/222#issuecomment-238738485
