### ISSUE TITLE
Add rdf-vocab 0.4.0 dependency and remove vocabs

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/active_fedora#651]

**Comment by dchandekstark** [comment]
Proposing to push this to 8.1, unless someone else want to make it happen stat.  I'd like to get 8.0.0 final out the door ASAP. @jcoyne @barmintor @acoburn

**Comment by acoburn** [comment]
Fine by me to push this to 8.1

**Comment by no-reply** [comment]
Closing as out of date.
