### ISSUE TITLE
Misleading 302 error from LDP when pointing to wrong Fedora URL

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra/active_fedora#656]
If fedora.yml points to /fedora instead of /fedora/rest, you get `Ldp::HttpError: STATUS: 302 ...` and an unhelpful backtrace.  

1. The 302 is misleading
2. A lot of people are going to run into this when they upgrade.  It should be handled with informative feedback (ie. check the fedora config for "/rest" and suggest that might be the problem if the url does not include it.

**Comment by hectorcorrea** [comment]
Fixed on PR #684
