### ISSUE TITLE
Incorporate Solrizer into ActiveFedora, It doesn't really have a purpose all alone.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#664]
What does everyone think about this proposal?

**Comment by hectorcorrea** [comment]
The code for the Solrizer gem seems small enough so moving the code here might not be a bad idea. 

Is the only reason for this proposal just that Solrizer have no purpose all alone or are the other reasons?

**Comment by cbeer** [comment]
We actually use solrizer without activefedora, in https://github.com/sul-dlss/spotlight-dor-resources and other places. Not that we need to, but the consistent API and suffixes are nice.

**Comment by jcoyne** [comment]
@cbeer Okay, that's reason enough to close this.
