### ISSUE TITLE
should stream large files to fedora instead of loading the file completely into memory before sending

### ISSUE THREAD

**Issue by cam156** [projecthydra/active_fedora#700]
Here at this line we load the content into memory:  
https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/file.rb#L254

This is Ok for small files, but for larger files we can cause the system to run out of memory.

It would we good to stream data to fedora and only read in smaller chunks.

Here is an example output of ActiveFedora running out of memory:
https://gist.github.com/cam156/e57521d8bbf9bc09d674

**Comment by jcoyne** [comment]
Closed by #701
