### ISSUE TITLE
The contains method should use LDP and use the /files/ container

### ISSUE THREAD

**Issue by escowles** [projecthydra/active_fedora#714]
Instead of writing files directly under a node, we should use an LDP container named /files/

**Comment by awead** [comment]
This has been enabled in #788. If you feel like verifying that it's done correctly, that would be very appreciated! :smile:

**Comment by escowles** [comment]
:+1:  I can confirm AF master now allows creating files under a /files/ container with the directly_contains directive:
`directly_contains :files, has_member_relation: ::RDF::URI.new("http://pcdm.org/models#hasFile")`
