### ISSUE TITLE
Allow rdf:type on ActiveFedora::File

### ISSUE THREAD

**Issue by awead** [projecthydra/active_fedora#792]
When creating a ActiveFedora:File resource you need to be able to set the rdf:type. A usage example of this would be to create an instance of a Hydra::PCDM::File which needs to the have the rdf:type pcdm:File.

To do this, execute a SPRQL update on the file's fcr:metadata resource, but have it update the file resource and not the actual fcr:metadata resource. So, given a uri `/rest/resource/file`, perform an update on `/rest/resource/file/fcr:metadata`:
```
PREFIX pcdm: <http://pcdm.org/models#>
INSERT {
  </rest/resource/file/> a pcdm:File
} WHERE {
}
```

**Comment by jcoyne** [comment]
@awead we're already doing this here: https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/models/file.rb#L6

Do you need something different?

**Comment by awead** [comment]
@jcoyne nope, that's it exactly. Although, I would have expected to be able to call `file.type` as I'm able to do with the ActiveFedora::Base, but maybe this is incorrect.

**Comment by jcoyne** [comment]
That's why I raised the question. It is possible to do what you ask, but maybe the API isn't what you expect.

**Comment by awead** [comment]
Anything wrong with adding:
``` ruby
def type
  self.metadata_node.query(predicate: RDF.type).map(&:object)
end
```
to ActiveFedora::File ?

**Comment by awead** [comment]
After taking a look, this isn't as straight-forward as I thought it was. I'm happy with querying the metadata node.
