### ISSUE TITLE
Can't delete Indirect Container proxies.

### ISSUE THREAD

**Issue by terrellt** [projecthydra/active_fedora#793]
```ruby
o.related_objects = [file1, file2]
o.save
o.related_objects = [file2]
# => undefined method delete_records
```

**Comment by terrellt** [comment]
https://dl.pushbulletusercontent.com/IVGvskRL2hfRloXxEZgrkhaLrDCs77U9/20150508_133630.jpg

Going to have to get the inbound relations on each file, compare them with the contains statements, and send delete requests for the intersection

**Comment by terrellt** [comment]
@jcoyne We could cut this down to x+1 statements if AF always asks for inbound relations. Do we know if that'd be a significant expense? @escowles?

**Comment by jcoyne** [comment]
@terrellt Give it a try. see if it works.

**Comment by terrellt** [comment]
@jcoyne Looks like something in the ActiveFedora pipeline is stripping subjects that aren't that object's URI before setting its resource

**Comment by terrellt** [comment]
Ah, found it.
