### ISSUE TITLE
Delete on indirect container

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/active_fedora#800]
Deleting an item in an indirect container seems to delete all items on it (not just the one item to be deleted) 

The following commit has a test to show this behavior: https://github.com/projecthydra/active_fedora/commit/df19ef937bcd87bc77511d774906ace32adf6c59 The tests fails because after deleting one of the two items in the indirect container both items are gone. 

This is the link to the branch: https://github.com/projecthydra/active_fedora/commits/indirect_container_delete_bug

@jcoyne @terrellt could you confirm this indeed a bug (and not a misunderstanding on how delete should be used) ?

**Comment by terrellt** [comment]
Huh. I'll take a look in an hour or so.

**Comment by terrellt** [comment]
Yup, this is what I get for relying on integration tests. Pushing up fix now.
