### ISSUE TITLE
Naming of contains, directly_contains, etc. on Reflection class is confusing 

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra/active_fedora#811]
Currently the association_class method in [reflection.rb](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/reflection.rb#L247-L266) does this:

```ruby
        when :contains
          Associations::BasicContainsAssociation      # This is a singular association that makes a Basic containment relationship  
        when :directly_contains
          Associations::DirectlyContainsAssociation   # This is a collection association that makes a Direct Containment relationship
        when :indirectly_contains
          Associations::IndirectlyContainsAssociation # This is a collection association that makes a Direct Containment relationship
        end
```

This is confusing for two reasons: 
* `contains` creates a SingularAssociation while `directly_contains` creates a CollectionAssociation
* `contains` is not clear.  Should explicitly declare that it's using basic containment, not direct containment or indirect containment (OR at least the documentation should call that out).

The main source of the confusion is that LDP has 3 types of container: Basic, Direct and Indirect.  AF has chosen to make :contains correspond to Basic containment, while :directly_contains and :indirectly_contains correspond to Direct and Indirect containment respectively.  From the LDP side, this makes sense but in terms of the ruby code it's confusing.

I don't know how to handle the Basic containment but, for starters, we need to add a few methods:

```ruby
        when :contains
         Associations::BasicContainsAssociation      # This is a singular association that makes a Basic containment relationship  
        when :directly_contains
          Associations::DirectlyContainsCollectionAssociation   # This is a collection association that makes a Direct Containment relationship
        when :indirectly_contains
          Associations::IndirectlyContainsCollectionAssociation # This is a collection association that makes a Indirect Containment relationship
        when :indirectly_contains_one
          Associations::IndirectlyContainsOneAssociation      # This is a singular association that filters an IndirectContainment relationship and returns the first matching node   
        when :directly_contains_one
          Associations::DirectlyContainsOneAssociation      # This is a singular association that filters an IndirectContainment relationship and returns the first matching node 
        end
```

**Comment by jcoyne** [comment]
contains is an LDP BasicContainer. I don't think it's possible for a basic container to have multiples.

**Comment by jcoyne** [comment]
contains is neither a Direct nor an Indirect container, it is a Basic Container See http://www.w3.org/TR/ldp/#ldpbc for the differences between the three.

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra/active_fedora/pull/1072
