### ISSUE TITLE
Can't remove objects from a ContainerAssociation

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra/active_fedora#815]
Currently there is no way to remove objects from a ContainerAssociation

This removes the `file_to_remove` from `generic_file.files` in memory, but the change does not persist to Fedora (even if you save `generic_file` and/or save `generic_file.files.proxy_association.container`)
```ruby
    generic_file.files.delete(file_to_remove)
```

... also, it looks like there is no way to delete/destroy ActiveFedora::File objects.

**Comment by terrellt** [comment]
@flyingzumwalt Is this a duplicate of https://github.com/projecthydra/active_fedora/issues/794 ? Indirect containers should work

**Comment by flyingzumwalt** [comment]
@terrellt yep.  it's a duplicate. Closing.
