### ISSUE TITLE
Prefer quick check of id before full object check

### ISSUE THREAD

**Issue by elrayle** [projecthydra/active_fedora#849]
Checking id and class first is more efficient than a full object check, so reverse the order evaluation to check full object equivalence only if id and class check fail.

**Comment by jcoyne** [comment]
Can you prove that? I think object.equal? Is just comparing the address of the object which is about the fastest thing you can do.

**Comment by elrayle** [comment]
I mistakenly was under the impression that the object equivalence test was comparing values.  It is not.  It is checking that the two objects being tested are indeed the exact same object living at the exact same address in memory.
