### ISSUE TITLE
Load_instance_from_solr has issues if model has properties that aren't saved in profile_json

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/active_fedora#856]
This issue comes up if you add new properties to your model and then try to load existing objects from Solr that don't have the new properties set in profile_json. If the new property is singular (i.e. has ```multiple: false```) then trying to read it will raise an error. If it's a multi-value property then reading it returns nil instead of an empty list. This only happens when you use load_instance_from_solr. If you load from Fedora then it behaves as expected, singular properties return nil and multi-value properties return an empty list.

I understand that arguably this might not really be a bug since you can reasonably be expected to perform some kind of a migration when changing the model. However, it would certainly be handy during development if new properties could be just simply added. And in any case, the behaviour should probably be consistent between loading from Fedora or Solr.

Below is a test case to demonstrate this. Can be placed in loadable_from_json_spec.rb.

```ruby
  context "unset fields in profile" do
    before do
      class UnsetTest < ActiveFedora::Base
      end
      @unset_test_id = UnsetTest.create.id
      Object.send(:remove_const, :UnsetTest)
      class UnsetTest < ActiveFedora::Base
        property :singular_field, multiple: false, predicate: ::RDF::URI('http://example.org/singular')
        property :multiple_field, multiple: true, predicate: ::RDF::URI('http://example.org/multiple')
      end
    end
    after do
      Object.send(:remove_const, :UnsetTest)
    end

    context "when loading from Solr" do
      subject { UnsetTest.load_instance_from_solr(@unset_test_id) }

      it "singular field should be nil" do
        expect(subject.singular_field).to be_nil
      end

      it "multiple field should be []" do
        expect(subject.multiple_field).to eql( [] )
      end
    end

    context "when loading from Fedora" do
      subject { UnsetTest.find(@unset_test_id) }

      it "singular field should be nil" do
        expect(subject.singular_field).to be_nil
      end

      it "multiple field should be []" do
        expect(subject.multiple_field).to eql( [] )
      end
    end

  end
```

And I also made a simple fix that'll pass the test but I'm not entirely confident that this is the right way to fix this or if I'm overlooking something else. I don't know the inner workings of Active Fedora that well. But if these look ok, I can certainly just make this a pull request.

```ruby
------------------- lib/active_fedora/loadable_from_json.rb -------------------
index d3e47b4..a38edbf 100644
@@ -117,7 +117,19 @@ module ActiveFedora
         attached_files[key] = SolrBackedMetadataFile.new
       end
       @resource = SolrBackedResource.new(self.class)
-      self.attributes = attrs.slice(*self.class.attribute_names)
+      new_attributes = {}
+      self.class.attribute_names.each do |a|
+        if !attrs.key? a
+          if self.class.reflect_on_property(a).multiple?
+            new_attributes[a] = []
+          else
+            new_attributes[a] = nil
+          end
+        else
+          new_attributes[a] = attrs[a]
+        end
+      end
+      self.attributes = new_attributes
       # TODO Should we clear the change tracking, or make this object Read-only?
 
       run_callbacks :find
```

**Comment by jcoyne** [comment]
This seems like a reasonable fix. You might want to make your additions
into its own method rather than push that logic into the existing method.
I'm sure a PR would be welcomed.

-Justin
