### ISSUE TITLE
AF::File::Attributes should find digests atop Fedora 4.3.0

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/active_fedora#883]
Fedora 4.3.0 was included in the latest commit of hydra-jetty, and 4.3.0 has [changes](https://wiki.duraspace.org/display/FF/Fedora+4.3.0+Release+Notes) to three Fedora-managed properties:

> This release is 4.3.0 instead of 4.2.1 because there are two non-backwards compatible changes: Several properties (mimetype, filename, digest, and cnd update) no longer use the fedora namespace.

`AF::File::Attributes` expects the digest property to be `Fcrepo4.digest` ([here](https://github.com/projecthydra/active_fedora/blob/d6784e23a7ad324e2d03a23c7c063fc888b89398/lib/active_fedora/file/attributes.rb#L18)) but that is no longer the case; now it's `PREMIS.hasMessageDigest`. (Also, not sure if these are elsewhere in the AF codebase but `Fcrepo4.mimeType` has changed to `EBUCore.hasMimeType` and `PREMIS.hasOriginalName` has changed to `EBUCore.filename`.)

Should AF master require a particular version of Fedora or should we make the code agnostic by, say, sniffing the version of Fedora and choosing the digest predicate based on that?

**Comment by grosscol** [comment]
Halfsies?  Could do sniffing now, and mark as deprecated for a future version.  Then pin that later version to AF > 4.3

**Comment by escowles** [comment]
I think we can just use the EBUCore.hasMimeType and EBUCore.filename with whatever version, so the checksum is the only thing that really depends on the version.  I think we should be able to just check to see whether we're getting fedora:digest or premis:hasMimeType and use the right one.

**Comment by mjgiarlo** [comment]
You can see the failures we're seeing in Sufia here: https://travis-ci.org/projecthydra/sufia/jobs/77663967
