### ISSUE TITLE
Should we use RDF::Vocab::Fcrepo4 instead of a local vocabulary?

### ISSUE THREAD

**Issue by escowles** [projecthydra/active_fedora#886]
RDF::Vocab has a Fcrepo4 vocabulary: https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/fcrepo4.rb -- switch to using it instead of ActiveFedora::RDF::Fcrepo4.

**Comment by jcoyne** [comment]
Yes.
