### ISSUE TITLE
ActiveFedor::File#refresh should clear @ds_content

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#913]
https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/file.rb#L103-L110

**Comment by hellbunnie** [comment]
There is also an @datastream_content variable being set here: https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/datastreams/nokogiri_datastreams.rb#L68

It's only used in this one place and it seems like it should be @ds_content instead.

Changing @datastream_content to @ds_content and clearing @ds_content in ActiveFedora::File#refresh fixes the issue where the old version of the xml datastream is returned by object.attached_files[:descMetadata].content after save. Only clearing @ds_content doesn't fix it as it gets reset to the previous value of @datastream_content later on.

clearing both @ds_content and @datastream_content would also do the trick.

I am writing a test for this, will probably fix and submit a pull request next week if I get a chance!
