### ISSUE TITLE
after_find not called in reload

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/active_fedora#961]
After_find callback is not called after calling ```#reload```. For example, if you do de/serialization between Fedora and Rails, then calling reload will give unexpected results due to deserialisation step being skipped.

```ruby
class Foo < ActiveFedora::Base
  attr_accessor :title
  property :title_serialized, multiple: false, predicate: ::RDF::Vocab::DC.title
  after_find :deserialize_title
  before_save :serialize_title

  def deserialize_title
    @title = (title_serialized || '').split(',').map(&:strip)
  end
  def serialize_title
    self.title_serialized = title.join(', ')
  end
end

f = Foo.create(title:['a', 'b'])
f.title # => ['a', 'b']
f2 = Foo.find(f.id)
f2.title = ['a', 'b', 'c']
f2.save
f.reload
f.title_serialized # => 'a, b, c'
f.title # => ['a', 'b']
Foo.find(f.id).title # => ['a', 'b', 'c']
```

Second to last line f.title should be ['a', 'b', 'c'] instead of ['a', 'b'].

I assume this can be fixed simply by adding run_callbacks [here](https://github.com/projecthydra/active_fedora/blob/a97e0ec9a637e461baad7563cfdcffec2fa47756/lib/active_fedora/core.rb#L59). If so, I can make a PR for this. Though I'm not sure if there are some other issues I haven't considered.

**Comment by jcoyne** [comment]
What is the behavior on an ActiveRecord class?  I don't want to deviate from that.

**Comment by jcoyne** [comment]
It looks like it does a find, and then copies all the attributes to the existing record:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L434-L441

**Comment by jcoyne** [comment]
I'm not sure why you're bothering with callbacks here. Why not just override the title accessors?

**Comment by ojlyytinen** [comment]
Yes, it looks like it does a find which I think calls the find callbacks on the fresh_object rather than the existing one. However, the example code above still doesn't work in ActiveRecord because the deserialized title is not in the attributes and wouldn't get copied to the existing record.

Good idea with overriding the accessors instead! Not sure why I didn't do that in the first place.

I'll close this issue then since the behaviour seems to be close to ActiveRecord already and overriding accessors is a better solution for my specific problem.
