### ISSUE TITLE
Whitespace entities not preserved in Fedora datastream

### ISSUE THREAD

**Issue by drh-stanford** [projecthydra/active_fedora#962]
The issue is that some entities, such as `&#xA;` are not preserved in the Fedora datastream. The problem, I believe, is that ActiveFedora sets the Fedora datastream content to be the `to_xml` output of the `Nokogiri::XML` document rather than the original verbatim content.

For example,

```
[1] pry(main)> doc = Nokogiri::XML.parse('<speak>Hello&#xA;World</speak>')
=> #(Document:0x3fc6c4477690 {
  name = "document",
  children = [ #(Element:0x3fc6c447fa34 { name = "speak", children = [ #(Text "Hello\nWorld")] })]
  })
[2] pry(main)> doc.to_xml
=> "<?xml version=\"1.0\"?>\n<speak>Hello\nWorld</speak>\n"
[3] pry(main)> 
```

The expected behavior would be that the `&#xA;` entity would be preserved in Fedora datastream.

**Comment by jcoyne** [comment]
ActiveFedora sets the datastream to be the to_xml output of the Nokogiri object which OM manipulates.  There is no way for us to do "verbatim" or we would loose the ability to manipulate it.  If Nokogiri is removing entities, perhaps you should report this as a bug at github.com/sparklemotion/nokogiri/issues/new

**Comment by cbeer** [comment]
Previously discussed at https://github.com/sparklemotion/nokogiri/issues/214.
